In [7]:
import pandas as pd

In [8]:
data = pd.read_csv('CatS_CHEMBL.csv')
data.head()

,Unnamed: 0,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,bao_endpoint,bao_format,bao_label,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,0,NaN,75990,[],CHEMBL658343,Inhibitory concentration against human recombi...,B,BAO_0000190,BAO_0000019,assay format,...,Homo sapiens,Cathepsin S,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,51.0
1,1,NaN,75991,[],CHEMBL658345,Equilibrium dissociation constant determined u...,B,BAO_0000034,BAO_0000357,single protein format,...,Homo sapiens,Cathepsin S,9606,NaN,NaN,Kd,nM,UO_0000065,NaN,4.0
2,2,NaN,75993,[],CHEMBL658343,Inhibitory concentration against human recombi...,B,BAO_0000190,BAO_0000019,assay format,...,Homo sapiens,Cathepsin S,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,9.0
3,3,NaN,75994,[],CHEMBL658345,Equilibrium dissociation constant determined u...,B,BAO_0000034,BAO_0000357,single protein format,...,Homo sapiens,Cathepsin S,9606,NaN,NaN,Kd,nM,UO_0000065,NaN,1.0
4,4,NaN,75996,[],CHEMBL658343,Inhibitory concentration against human recombi...,B,BAO_0000190,BAO_0000019,assay format,...,Homo sapiens,Cathepsin S,9606,NaN,NaN,IC50,nM,UO_0000065,NaN,11000.0

In [9]:
#_Create new dataframe with useful columns

useful_data = {'smiles': data['canonical_smiles'], 'IC50': data['standard_value'], 
               'pchembl': data['pchembl_value'], 'type': data['standard_type'], 
               'ID' : data['molecule_chembl_id'] }

data_new  = pd.DataFrame(useful_data)
data_new.head()

,smiles,IC50,pchembl,type,ID
0,CC(C)C[C@H](NC(=O)N1CCOCC1)C(=O)N[C@H](C#N)c2c...,51.0,7.29,IC50,CHEMBL347745
1,CC(C)C[C@H](NC(=O)N1CCOCC1)C(=O)N[C@H](C#N)c2c...,4.0,8.40,Kd,CHEMBL347745
2,O=C(N[C@H](C#N)c1ccccc1)[C@H](CC2CCCCC2)NC(=O)...,9.0,8.05,IC50,CHEMBL435440
3,O=C(N[C@H](C#N)c1ccccc1)[C@H](CC2CCCCC2)NC(=O)...,1.0,9.00,Kd,CHEMBL435440
4,CC(C)C[C@@H](NC(=O)N1CCOCC1)C(=O)N[C@@H](CCc2c...,11000.0,4.96,IC50,CHEMBL151641

In [14]:
#_Remove all rows that doesn't correspond to IC50

cleaned_data = data_new[data_new['type'] == 'IC50']
cleaned_data = cleaned_data.reset_index(drop = True)
cleaned_data = cleaned_data.sort_values(by=['ID'])
cleaned_data.dropna(inplace=True)
cleaned_data.head()

,smiles,IC50,pchembl,type,ID
875,CN(C)CCSc1cc(ccc1C(F)(F)F)c2nn(CCCN3CCC(CC3)N4...,1280.0,5.89,IC50,CHEMBL1076795
895,CN(C)c1ccc(cc1)C(=O)NCCSc2cc(ccc2C(F)(F)F)c3nn...,530.0,6.28,IC50,CHEMBL1076796
850,CCCc1cc(nc(n1)C#N)c2cccc(c2)C(C)(C)C,191.0,6.72,IC50,CHEMBL1077193
1161,CCCc1cc(nc(n1)C#N)c2cccc(c2)C(C)(C)C,191.0,6.72,IC50,CHEMBL1077193
857,CCCc1cc(nc(n1)C#N)C2CCCCCCC2,2239.0,5.65,IC50,CHEMBL1077194

In [15]:
cleaned_data.shape

(1827, 5)

In [16]:
#_Remove duplicates using CHEMBL ID

cleaned_data.drop_duplicates(subset = 'ID', keep = 'first', inplace = True)
cleaned_data.shape

(1582, 5)

In [17]:
cleaned_data.to_csv('cleaned_CatS_CHEMBL.csv')